### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by RyanCR03** [OreCruncher/SoundControl#6]
Crash on startup...

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/8/20 12:01 PM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at org.orecruncher.sndctrl.audio.handlers.SoundEventHandling.onGuiOpen(SoundEventHandling.java:81) ~[?:1.14.4-0.0.5.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_115_SoundEventHandling_onGuiOpen_GuiOpenEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:758) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:screenshotclipboard:coremodone,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$init$3(Minecraft.java:550) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:screenshotclipboard:coremodone,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3651/1710441966.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.render(ResourceLoadProgressGui.java:132) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:875) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:cmdcam:changeMouseOver,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:screenshotclipboard:coremodone,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:screenshotclipboard:coremodone,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.116.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/813455850.call(Unknown Source) [forge-1.14.4-28.1.116.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.orecruncher.sndctrl.audio.handlers.SoundEventHandling.onGuiOpen(SoundEventHandling.java:81)
	at net.minecraftforge.eventbus.ASMEventHandler_115_SoundEventHandling_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:758)
	at net.minecraft.client.Minecraft.lambda$init$3(Minecraft.java:550)
	at net.minecraft.client.Minecraft$$Lambda$3651/1710441966.run(Unknown Source)
	at net.minecraft.client.gui.ResourceLoadProgressGui.render(ResourceLoadProgressGui.java:132)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:875)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/813455850.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5273599440 bytes (5029 MB) / 6341787648 bytes (6048 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar runtimedistcleaner PLUGINSERVICE 
		/Optifine%201.14.4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.116.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.116
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		forge-1.14.4-28.1.116-client.jar Minecraft {minecraft@1.14.4 DONE}
		AmbientSounds_v3.0.14_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		SoundControl-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eSound Control {sndctrl@1.14.4-0.0.5.0 DONE}
		Environs-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eEnvirons {environs@1.14.4-0.0.5.0 DONE}
		winterambience-1.0.0 (1).jar Winter Ambience {winterambience@1.0.0 DONE}
		CMDCam_v1.5.1_mc1.14.4.jar CMDCam {cmdcam@1.5.0 DONE}
		CreativeCore_v2.0.0_mc1.14.4 (1).jar CreativeCore {creativecore@2.0.0 DONE}
		rys-0.1.18.jar Ready Your Shovels {rys@0.1.18 DONE}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 DONE}
		bambooblocks-1.2.11.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		MinecraftCapes Forge 1.14.4 (1).jar James090500's MinecraftCapes Mod {minecraftcapes@9.8 DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		cosmeticbeds-FORGE-1.14.4-2.0.0.1.jar Cosmetic Beds {cosmeticbeds@FORGE-1.14.4-2.0.0.1 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.9.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		MobEffects-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eMob Effects {mobeffects@1.14.4-0.0.5.0 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		comforts-FORGE-1.14.4-2.0-beta4 (1).jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		The-Endergetic-Expansion-1.14.4-v1.1.2.jar The Endergetic Expansion {endergetic@1.1.2 DONE}
		ScreenshotToClipboard-1.14.4-1.0.3.jar Screenshot to Clipboard {screenshotclipboard@1.14.4-1.0.3 DONE}
		randompatches-1.14.4-1.21.0.0.jar RandomPatches {randompatches@1.14.4-1.21.0.0 DONE}
		ForgivingVoid_1.14.4-3.0.8 (1).jar Forgiving Void {forgivingvoid@3.0.8 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		authme-1.14_1.15-1.1.1.jar Auth Me {authme@1.1.1 DONE}
		CustomMCreatorMod.jar MineKart {minekart@1.0.0 DONE}
		carpetstairsmod-1.0.jar Carpet Stairs Mod {carpetstairsmod@1.0 DONE}
		immersive-portals-0.13(for+mc+1.14+with+forge).jar Immersive Portals {immersive_portals@0.13 DONE}
		swampexpansion-1.3.jar Swamp Expansion {swampexpansion@1.3 DONE}
		Charm-1.14.4-1.4.3 (1).jar Charm {charm@1.14.4-1.4.3 DONE}
		forge-1.14.4-28.1.116-universal.jar Forge {forge@28.1.116 DONE}
		Quark-r2.0-210.jar Quark {quark@r2.0-210 DONE}
		GameMenuModOption-1.14.4-1.0.0.jar GameMenuModOption {gamemenumodoption@1.0.0 DONE}
	Launched Version: 1.14.4-forge-28.1.116
	LWJGL: 3.2.2 build 10
	OpenGL: Radeon RX 560 Series GL version 4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/MineKart Resource Pack (incompatible)
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5_pre1
	OptiFine Build: 20191129-142909
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007
	OpenGlRenderer: Radeon RX 560 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by OreCruncher** [comment]
I will need the client side log to understand the startup sequence.  Also post a link to the Sound Control config.

**Comment by OreCruncher** [comment]
I made a speculative fix (can't test but I suspect).  Pushed release build 0.1.0.0 to CurseForge
